# -*- coding: utf-8 -*-
"""drive_upload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C4Sv5oWVbEXP9S3_i5mL8mqyVYb3aVzt
"""

#!pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
# Authenticate user to access Google Drive
from google.colab import auth                  # Imports the auth module from google.colab library
auth.authenticate_user()                       # Authenticates the user to access Google APIs
from google.colab import drive                 # Imports the drive module from google.colab library
drive.mount('/content/drive')                  # Mounts the Google Drive to the current runtime environment


from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
import io

file_ids = ['1UnA5RjwMlYqyxn_n6rGpABbuzGCKxLUvYbOmZwFRryI','1C3dGzGTmv3urH918GRQ0Nyw2ADWKOlxnHFqtOSN3wzk']   #https://docs.google.com/document/d/1UnA5RjwMlYqyxn_n6rGpABbuzGCKxLUvYbOmZwFRryI/edit?usp=sharing

text_list = []
for file_id in file_ids:

  # Authenticate and construct the service object
  drive_service = build('drive', 'v3')
  doc = drive_service.files().get(fileId=file_id).execute()
  doc_content = drive_service.files().export(fileId=file_id, mimeType='text/plain').execute()
  content = doc_content.decode('utf-8')
  # Read the local text file and add its content to text_list
  with open(f'{file_id}.txt', 'r') as f:
  text_list.append(f.read())